# Generated by Django 5.2 on 2026-05-23 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objective', models.TextField(blank=True, help_text='What the user is expected to accomplish.')),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=15)),
                ('technology', models.CharField(choices=[('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript / Node.js'), ('RUST', 'Rust'), ('GO', 'Go'), ('C', 'C / C++'), ('JAVA', 'Java'), ('BASH', 'Bash / Shell'), ('GENERIC', 'Generic Linux')], default='GENERIC', max_length=15)),
                ('docker_image', models.CharField(max_length=300)),
                ('port_range_start', models.PositiveIntegerField(default=10000)),
                ('port_range_end', models.PositiveIntegerField(default=20000)),
                ('time_limit', models.PositiveIntegerField(default=3600, help_text='Session time limit in seconds.')),
                ('environment_vars', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lab',
                'verbose_name_plural': 'Labs',
                'ordering': ['difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(blank=True, max_length=100)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STARTING', 'Starting'), ('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='STARTING', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='labyrinth.lab')),
            ],
            options={
                'verbose_name': 'Lab Session',
                'verbose_name_plural': 'Lab Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
