# Generated by Django 5.2 on 2026-05-23 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('rust', 'Rust'), ('go', 'Go'), ('c', 'C'), ('cpp', 'C++'), ('java', 'Java'), ('bash', 'Bash'), ('sql', 'SQL'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('yaml', 'YAML'), ('markdown', 'Markdown'), ('other', 'Other')], default='python', max_length=20)),
                ('code', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, default='Untitled Session', max_length=200)),
                ('is_public', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Code Session',
                'verbose_name_plural': 'Code Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('rust', 'Rust'), ('go', 'Go'), ('c', 'C'), ('cpp', 'C++'), ('java', 'Java'), ('bash', 'Bash'), ('sql', 'SQL'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('yaml', 'YAML'), ('markdown', 'Markdown'), ('other', 'Other')], default='python', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Code Snippet',
                'verbose_name_plural': 'Code Snippets',
                'ordering': ['-created_at'],
            },
        ),
    ]
