# Generated by Django 5.2 on 2026-05-23 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codesession',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_code_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
