# Generated by Django 5.2 on 2026-05-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('new_challenges', models.PositiveIntegerField(default=0)),
                ('submissions', models.PositiveIntegerField(default=0)),
                ('correct_submissions', models.PositiveIntegerField(default=0)),
                ('lab_sessions_started', models.PositiveIntegerField(default=0)),
                ('articles_published', models.PositiveIntegerField(default=0)),
                ('snippets_shared', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Stats',
                'verbose_name_plural': 'Platform Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('source', models.CharField(blank=True, help_text='Module or component that generated this log.', max_length=200)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Additional structured data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='matrix_syst_level_a6b1dd_idx'), models.Index(fields=['source'], name='matrix_syst_source_5329f2_idx')],
            },
        ),
    ]
